create database memes;
use memes;
show databases;
DROP DATABASE memes;
CREATE TABLE memeinfo (id integer NOT NULL,name varchar(30) NOT NULL, url varchar(1000) NOT NULL, caption varchar(500) NOT NULL);
ALTER TABLE memeinfo MODIFY id integer NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST;
INSERT INTO memeinfo (name,url,caption) VALUES ('Harry','https://images.indianexpress.com/2019/10/IRCTC-1200-2.jpg','IRCTC Meme');
INSERT INTO memeinfo (name,url,caption) VALUES ('Kevin','https://static.businessworld.in/article/article_extra_large_image/1530772981_sqeqcy_Funny-marketing-meme-concept-470.jpg','Marketing Meme');
INSERT INTO memeinfo (name,url,caption) VALUES ('Johnny','https://i.imgflip.com/1l6uou.jpg','OOPS Meme');
SELECT * FROM memeinfo;